### ISSUE TITLE
Just use ytdlp for downloading.

### ISSUE THREAD

**Issue by sanjit-sinha** [AvAkanksh/My-Python-Codes#1]

**Comment by AvAkanksh** [comment]
which project are u refering to @sanjit-sinha ?

**Comment by AvAkanksh** [comment]
I have used aria2c because it was written in c++ and it is lightweight compared to yt-dlp

**Comment by sanjit-sinha** [comment]
Yes aria2c is great choice. But i suggested yt-dlp because it also use aria2c (need some additional flag) and on top of that it provides many more features wich is super helpful.

**Comment by AvAkanksh** [comment]
understood. Thanks for the insights 😄
